#!/usr/bin/env php
<?php

if(strpos(basename(__FILE__), 'phar') !== false){
    include 'phar://exakat.phar/library/Autoload.php';
} else {
    include __DIR__.'/library/Autoload.php';
}

try {
    if (isset($argv)) {
        $config = \Config::factory($argv);
    } else {
        $config = \Config::factory($GLOBALS['argv']);
    }

    $graphDB = new \Graph\Gremlin2($config);

    $exakat = new \Exakat($graphDB);
    $exakat->execute($config);
} catch (\Exceptions\NoPhpBinary $e) {
    print "\nExakat configuration error : ".$e->getMessage()."\n";
    print "Aborting\n";
} catch (\Exceptions\NoResultsFromGremlin $e) {
    print "\nGraphDB didn't return results error : ".$e->getMessage()."\n";
    print "Aborting\n";
} catch (\RuntimeException $e) {
    print "\nRuntime error : ".$e->getMessage()."\n";
    print "Aborting\n";
}

