#!/usr/bin/env php
<?php

try {
    $isPhar = basename(__FILE__);
    if (substr($isPhar, -5) == '.phar') { 
        $isPhar = substr($isPhar, 0, -5);
    }
    Phar::mapPhar();
} catch (PharException $e) {
    $isPhar = false;
}

if($isPhar === false){
    include __DIR__.'/library/Autoload.php';
} else {
    include 'phar://'.$isPhar.'.phar/library/Autoload.php';
}

$graphDB = new \Graph\Gremlin3($config);

__HALT_COMPILER();