<?php

class x {
//public function __halt_compiler() {}
public function abstract() {}
public function and() {}
public function array() {}
public function as() {}
public function break() {}
public function case() {}
public function catch() {}
public function class() {}
public function clone() {}
public function const() {}
public function continue() {}
public function declare() {}
public function default() {}
public function die() {}
public function do() {}
public function echo() {}
public function else() {}
public function elseif() {}
public function empty() {}
public function enddeclare() {}
public function endfor() {}
public function endforeach() {}
public function endif() {}
public function endswitch() {}
public function endwhile() {}
public function eval() {}
public function exit() {}
public function extends() {}
public function final() {}
public function finally() {}
public function for() {}
public function foreach() {}
public function function() {}
public function global() {}
public function goto() {}
public function if() {}
public function implements() {}
public function include() {}
public function include_once() {}
public function instanceof() {}
public function insteadof() {}
public function interface() {}
public function isset() {}
public function list() {}
public function namespace() {}
public function new() {}
public function or() {}
public function print() {}
public function private() {}
public function protected() {}
public function public() {}
public function require() {}
public function require_once() {}
public function return() {}
public function static() {}
public function switch() {}
public function throw() {}
public function trait() {}
public function try() {}
public function unset() {}
public function use() {}
public function var() {}
public function while() {}
public function xor() {}
public function yield() {}
}