#!/usr/bin/env php
<?php
/*
 * Copyright 2012-2015 Damien Seguy – Exakat Ltd <contact(at)exakat.io>
 * This file is part of Exakat.
 *
 * Exakat is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Exakat is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Exakat.  If not, see <http://www.gnu.org/licenses/>.
 *
 * The latest code can be found at <http://exakat.io/>.
 *
*/

use Everyman\Neo4j\Client,
	Everyman\Neo4j\Index\NodeIndex,
	Everyman\Neo4j\Relationship,
	Everyman\Neo4j\Node,
	Everyman\Neo4j\Gremlin,
	Tokenizer\Token;

include_once(dirname(__DIR__).'/library/Autoload.php');
spl_autoload_register('Autoload::autoload_library');

$client = new Client();

$query = <<<'QUERY'

/// insert a query here

QUERY;

$res = query($query);



foreach($res as $k => $v) {
    print_r($k);
    print_r($v[0]);
    print "\n";
}

function queryOne($query) {
    $r = query($query);
    return $r[0][0];
}

function queryArray($query) {
    $return = array();
    
    $result = query($query);
    foreach($result as $r) {
        $return[] = (array) $r[0];
    }
	
	return $return;
}

function queryColumn($query) {
    $return = array();
    
    $result = query($query);
    foreach($result as $r) {
        $return[] = $r[0];
    }
	
	return $return;
}

function query($query) {
    global $client;
    $params = array('type' => 'IN');
    $query = new Gremlin\Query($client, $query, $params);
    return $query->getResultSet();
}

function table_encode($stats) {
    $html = "<html><body>";
    
    foreach($stats as $name => $value) {
        $html .= "<tr><td>$name</td><td>$value</td></tr>\n";
    }
    
    $html .= "</body></html>";
    return $html;
}

function text_encode($stats) {
    global $file;
    if ($file) {
        $html = "Statistics for the file '$file'\n\n";
    } else {
        $html = "Statistics for the whole server\n\n";
    }
    
    foreach($stats as $name => $value) {
        if (is_array($value)) {
            $html .= "$name : ".join(" \n".str_repeat(' ', strlen("$name : ")), $value)."\n";
        } else {
            $html .= "$name : $value\n";
        }
    }
    
    $html .= "\n";
    return $html;
}

?>