<?php

$expected     = array(
'@preg_replace(\' ÇebÇe\', null, $r)',
'@preg_replace(\'  ÇebÇe\', null, $r)',
'@preg_replace(\'ÉecÉe\', null, $r)',
'@preg_replace(\' ÉecÉe\', null, $r)',
'@preg_replace(\'ÅeaÅe\', null, $r)',
'@preg_replace(\' ÅeaÅe\', null, $r)',
'@preg_replace(\'  ÅeaÅe\', null, $r)',
'@preg_replace(\'ÇebÇe\', null, $r)',
'@preg_replace(\'  dye\', null, $r)',
'@preg_replace(\'ÄdzÄe\', null, $r)',
'@preg_replace(\' ÄdzÄe\', null, $r)',
'@preg_replace(\'  ÄdzÄe\', null, $r)',
'@preg_replace(\' ~dx~e\', null, $r)',
'@preg_replace(\'  ~dx~e\', null, $r)',
'@preg_replace(\'dye\', null, $r)',
'@preg_replace(\' dye\', null, $r)',
'@preg_replace(\'àehàe\', null, $r)',
'@preg_replace(\'  áegáe\', null, $r)',
'@preg_replace(\'  àehàe\', null, $r)',
'@preg_replace(\' àehàe\', null, $r)',
'@preg_replace(\'  ÜefÜe\', null, $r)',
'@preg_replace(\' ÜefÜe\', null, $r)',
'@preg_replace(\' áegáe\', null, $r)',
'@preg_replace(\'áegáe\', null, $r)',
'@preg_replace(\' ÖeeÖe\', null, $r)',
'@preg_replace(\'ÖeeÖe\', null, $r)',
'@preg_replace(\'ÜefÜe\', null, $r)',
'@preg_replace(\'  ÖeeÖe\', null, $r)',
'@preg_replace(\'ÑedÑe\', null, $r)',
'@preg_replace(\'  ÉecÉe\', null, $r)',
'@preg_replace(\'  ÑedÑe\', null, $r)',
'@preg_replace(\' ÑedÑe\', null, $r)',
'@preg_replace(\'  çemçe\', null, $r)',
'@preg_replace(\'éenée\', null, $r)',
'@preg_replace(\'çemçe\', null, $r)',
'@preg_replace(\' çemçe\', null, $r)',
'@preg_replace(\' åelåe\', null, $r)',
'@preg_replace(\'  åelåe\', null, $r)',
'@preg_replace(\'  ãekãe\', null, $r)',
'@preg_replace(\'åelåe\', null, $r)',
'@preg_replace(\'ãekãe\', null, $r)',
'@preg_replace(\' ãekãe\', null, $r)',
'@preg_replace(\' äejäe\', null, $r)',
'@preg_replace(\'  äejäe\', null, $r)',
'@preg_replace(\'  âeiâe\', null, $r)',
'@preg_replace(\'äejäe\', null, $r)',
'@preg_replace(\'âeiâe\', null, $r)',
'@preg_replace(\' âeiâe\', null, $r)',
'@preg_replace(\' ìesìe\', null, $r)',
'@preg_replace(\'ìesìe\', null, $r)',
'@preg_replace(\'  íeríe\', null, $r)',
'@preg_replace(\' íeríe\', null, $r)',
'@preg_replace(\'íeríe\', null, $r)',
'@preg_replace(\'  ëeqëe\', null, $r)',
'@preg_replace(\' ëeqëe\', null, $r)',
'@preg_replace(\'ëeqëe\', null, $r)',
'@preg_replace(\'  êepêe\', null, $r)',
'@preg_replace(\' êepêe\', null, $r)',
'@preg_replace(\'êepêe\', null, $r)',
'@preg_replace(\'  èeoèe\', null, $r)',
'@preg_replace(\' èeoèe\', null, $r)',
'@preg_replace(\'èeoèe\', null, $r)',
'@preg_replace(\'  éenée\', null, $r)',
'@preg_replace(\' éenée\', null, $r)',
'@preg_replace(\' ñevñe\', null, $r)',
'@preg_replace(\'  ñevñe\', null, $r)',
'@preg_replace(\'óewóe\', null, $r)',
'@preg_replace(\' óewóe\', null, $r)',
'@preg_replace(\'  óewóe\', null, $r)',
'@preg_replace(\'òexòe\', null, $r)',
'@preg_replace(\' òexòe\', null, $r)',
'@preg_replace(\'  òexòe\', null, $r)',
'@preg_replace(\'  ìesìe\', null, $r)',
'@preg_replace(\'îetîe\', null, $r)',
'@preg_replace(\' îetîe\', null, $r)',
'@preg_replace(\'  îetîe\', null, $r)',
'@preg_replace(\'ïeuïe\', null, $r)',
'@preg_replace(\' ïeuïe\', null, $r)',
'@preg_replace(\'  ïeuïe\', null, $r)',
'@preg_replace(\'ñevñe\', null, $r)',
'@preg_replace(\'úfbúe\', null, $r)',
'@preg_replace(\'  õfaõe\', null, $r)',
'@preg_replace(\'  úfbúe\', null, $r)',
'@preg_replace(\' úfbúe\', null, $r)',
'@preg_replace(\' ùfcùe\', null, $r)',
'@preg_replace(\'ùfcùe\', null, $r)',
'@preg_replace(\'ûfdûe\', null, $r)',
'@preg_replace(\'  ùfcùe\', null, $r)',
'@preg_replace(\' ôeyôe\', null, $r)',
'@preg_replace(\'ôeyôe\', null, $r)',
'@preg_replace(\'öezöe\', null, $r)',
'@preg_replace(\'  ôeyôe\', null, $r)',
'@preg_replace(\'  öezöe\', null, $r)',
'@preg_replace(\' öezöe\', null, $r)',
'@preg_replace(\' õfaõe\', null, $r)',
'@preg_replace(\'õfaõe\', null, $r)',
'@preg_replace(\'  °fg°e\', null, $r)',
'@preg_replace(\'¢fh¢e\', null, $r)',
'@preg_replace(\'°fg°e\', null, $r)',
'@preg_replace(\' °fg°e\', null, $r)',
'@preg_replace(\'£fi£e\', null, $r)',
'@preg_replace(\' £fi£e\', null, $r)',
'@preg_replace(\' ¢fh¢e\', null, $r)',
'@preg_replace(\'  ¢fh¢e\', null, $r)',
'@preg_replace(\'üfeüe\', null, $r)',
'@preg_replace(\' üfeüe\', null, $r)',
'@preg_replace(\' ûfdûe\', null, $r)',
'@preg_replace(\'  ûfdûe\', null, $r)',
'@preg_replace(\' †ff†e\', null, $r)',
'@preg_replace(\'  †ff†e\', null, $r)',
'@preg_replace(\'  üfeüe\', null, $r)',
'@preg_replace(\'†ff†e\', null, $r)',
'@preg_replace(\' ßfmße\', null, $r)',
'@preg_replace(\'ßfmße\', null, $r)',
'@preg_replace(\'  ¶fl¶e\', null, $r)',
'@preg_replace(\' ¶fl¶e\', null, $r)',
'@preg_replace(\'  ®fn®e\', null, $r)',
'@preg_replace(\' ®fn®e\', null, $r)',
'@preg_replace(\'®fn®e\', null, $r)',
'@preg_replace(\'  ßfmße\', null, $r)',
'@preg_replace(\'  §fj§e\', null, $r)',
'@preg_replace(\' §fj§e\', null, $r)',
'@preg_replace(\'§fj§e\', null, $r)',
'@preg_replace(\'  £fi£e\', null, $r)',
'@preg_replace(\'¶fl¶e\', null, $r)',
'@preg_replace(\'  •fk•e\', null, $r)',
'@preg_replace(\' •fk•e\', null, $r)',
'@preg_replace(\'•fk•e\', null, $r)',
'@preg_replace(\'  ™fp™e\', null, $r)',
'@preg_replace(\' ™fp™e\', null, $r)',
'@preg_replace(\' ´fq´e\', null, $r)',
'@preg_replace(\'´fq´e\', null, $r)',
'@preg_replace(\' ©fo©e\', null, $r)',
'@preg_replace(\'©fo©e\', null, $r)',
'@preg_replace(\'™fp™e\', null, $r)',
'@preg_replace(\'  ©fo©e\', null, $r)',
'@preg_replace(\' ≠fs≠e\', null, $r)',
'@preg_replace(\'≠fs≠e\', null, $r)',
'@preg_replace(\'ÆftÆe\', null, $r)',
'@preg_replace(\'  ≠fs≠e\', null, $r)',
'@preg_replace(\'¨fr¨e\', null, $r)',
'@preg_replace(\'  ´fq´e\', null, $r)',
'@preg_replace(\'  ¨fr¨e\', null, $r)',
'@preg_replace(\' ¨fr¨e\', null, $r)',
'@preg_replace(\'  ØfuØe\', null, $r)',
'@preg_replace(\'∞fv∞e\', null, $r)',
'@preg_replace(\' ∞fv∞e\', null, $r)',
'@preg_replace(\'  ∞fv∞e\', null, $r)',
'@preg_replace(\' ÆftÆe\', null, $r)',
'@preg_replace(\'  ÆftÆe\', null, $r)',
'@preg_replace(\'ØfuØe\', null, $r)',
'@preg_replace(\' ØfuØe\', null, $r)',
'@preg_replace(\' ≤fx≤e\', null, $r)',
'@preg_replace(\'  ≤fx≤e\', null, $r)',
'@preg_replace(\'≥fy≥e\', null, $r)',
'@preg_replace(\' ≥fy≥e\', null, $r)',
'@preg_replace(\'±fw±e\', null, $r)',
'@preg_replace(\' ±fw±e\', null, $r)',
'@preg_replace(\'  ±fw±e\', null, $r)',
'@preg_replace(\'≤fx≤e\', null, $r)',
'@preg_replace(\'∂gb∂e\', null, $r)',
'@preg_replace(\'  µgaµe\', null, $r)',
'@preg_replace(\' µgaµe\', null, $r)',
'@preg_replace(\'µgaµe\', null, $r)',
'@preg_replace(\'  ¥fz¥e\', null, $r)',
'@preg_replace(\' ¥fz¥e\', null, $r)',
'@preg_replace(\'¥fz¥e\', null, $r)',
'@preg_replace(\'  ≥fy≥e\', null, $r)',
'@preg_replace(\'  ∏gd∏e\', null, $r)',
'@preg_replace(\' ∏gd∏e\', null, $r)',
'@preg_replace(\'∏gd∏e\', null, $r)',
'@preg_replace(\'  ∑gc∑e\', null, $r)',
'@preg_replace(\' ∑gc∑e\', null, $r)',
'@preg_replace(\'∑gc∑e\', null, $r)',
'@preg_replace(\'  ∂gb∂e\', null, $r)',
'@preg_replace(\' ∂gb∂e\', null, $r)',
'@preg_replace(\'ªggªe\', null, $r)',
'@preg_replace(\' ªggªe\', null, $r)',
'@preg_replace(\' ∫gf∫e\', null, $r)',
'@preg_replace(\'  ∫gf∫e\', null, $r)',
'@preg_replace(\'  πgeπe\', null, $r)',
'@preg_replace(\'∫gf∫e\', null, $r)',
'@preg_replace(\'πgeπe\', null, $r)',
'@preg_replace(\' πgeπe\', null, $r)',
'@preg_replace(\'  ΩgiΩe\', null, $r)',
'@preg_replace(\'ægjæe\', null, $r)',
'@preg_replace(\'ΩgiΩe\', null, $r)',
'@preg_replace(\' ΩgiΩe\', null, $r)',
'@preg_replace(\' ºghºe\', null, $r)',
'@preg_replace(\'  ºghºe\', null, $r)',
'@preg_replace(\'  ªggªe\', null, $r)',
'@preg_replace(\'ºghºe\', null, $r)',
'@preg_replace(\'  ægjæe\', null, $r)',
'@preg_replace(\' ægjæe\', null, $r)',
'@preg_replace(\' øgkøe\', null, $r)',
'@preg_replace(\'øgkøe\', null, $r)',
'@preg_replace(\'¿gl¿e\', null, $r)',
'@preg_replace(\'  øgkøe\', null, $r)',
'@preg_replace(\'  ¿gl¿e\', null, $r)',
'@preg_replace(\' ¿gl¿e\', null, $r)',
'@preg_replace(\' ¡gm¡e\', null, $r)',
'@preg_replace(\'¡gm¡e\', null, $r)',
'@preg_replace(\'¬gn¬e\', null, $r)',
'@preg_replace(\'  ¡gm¡e\', null, $r)',
'@preg_replace(\'  ¬gn¬e\', null, $r)',
'@preg_replace(\' ¬gn¬e\', null, $r)',
'@preg_replace(\' √go√e\', null, $r)',
'@preg_replace(\'√go√e\', null, $r)',
'@preg_replace(\'  √go√e\', null, $r)',
'@preg_replace(\'ƒgpƒe\', null, $r)',
'@preg_replace(\' ƒgpƒe\', null, $r)',
'@preg_replace(\'  ƒgpƒe\', null, $r)',
'@preg_replace(\'≈gq≈e\', null, $r)',
'@preg_replace(\' ≈gq≈e\', null, $r)',
'@preg_replace(\'  ≈gq≈e\', null, $r)',
'@preg_replace(\'∆gr∆e\', null, $r)',
'@preg_replace(\' ∆gr∆e\', null, $r)',
'@preg_replace(\'  ∆gr∆e\', null, $r)',
'@preg_replace(\'«gs«e\', null, $r)',
'@preg_replace(\' «gs«e\', null, $r)',
'@preg_replace(\'  «gs«e\', null, $r)',
'@preg_replace(\'»gt»e\', null, $r)',
'@preg_replace(\' »gt»e\', null, $r)',
'@preg_replace(\'  »gt»e\', null, $r)',
'@preg_replace(\' gv e\', null, $r)',
'@preg_replace(\'  …gu…e\', null, $r)',
'@preg_replace(\' …gu…e\', null, $r)',
'@preg_replace(\'…gu…e\', null, $r)',
'@preg_replace(\' ÀgwÀe\', null, $r)',
'@preg_replace(\'ÀgwÀe\', null, $r)',
'@preg_replace(\'   gv e\', null, $r)',
'@preg_replace(\'  gv e\', null, $r)',
'@preg_replace(\'  ÃgxÃe\', null, $r)',
'@preg_replace(\' ÃgxÃe\', null, $r)',
'@preg_replace(\'ÃgxÃe\', null, $r)',
'@preg_replace(\'  ÀgwÀe\', null, $r)',
'@preg_replace(\'ŒgzŒe\', null, $r)',
'@preg_replace(\'  ÕgyÕe\', null, $r)',
'@preg_replace(\' ÕgyÕe\', null, $r)',
'@preg_replace(\'ÕgyÕe\', null, $r)',
'@preg_replace(\'œhaœe\', null, $r)',
'@preg_replace(\' œhaœe\', null, $r)',
'@preg_replace(\' ŒgzŒe\', null, $r)',
'@preg_replace(\'  ŒgzŒe\', null, $r)',
'@preg_replace(\' –hb–e\', null, $r)',
'@preg_replace(\'  –hb–e\', null, $r)',
'@preg_replace(\'  œhaœe\', null, $r)',
'@preg_replace(\'–hb–e\', null, $r)',
'@preg_replace(\'  —hc—e\', null, $r)',
'@preg_replace(\'“hd“e\', null, $r)',
'@preg_replace(\'—hc—e\', null, $r)',
'@preg_replace(\' —hc—e\', null, $r)',
'@preg_replace(\'”he”e\', null, $r)',
'@preg_replace(\' ”he”e\', null, $r)',
'@preg_replace(\' “hd“e\', null, $r)',
'@preg_replace(\'  “hd“e\', null, $r)',
'@preg_replace(\'ﬁhpﬁe\', null, $r)',
'@preg_replace(\'  ›ho›e\', null, $r)',
'@preg_replace(\' ›ho›e\', null, $r)',
'@preg_replace(\'›ho›e\', null, $r)',
'@preg_replace(\'  ‹hn‹e\', null, $r)',
'@preg_replace(\' ‹hn‹e\', null, $r)',
'@preg_replace(\'‹hn‹e\', null, $r)',
'@preg_replace(\'  €hm€e\', null, $r)',
'@preg_replace(\' €hm€e\', null, $r)',
'@preg_replace(\'€hm€e\', null, $r)',
'@preg_replace(\'  ⁄hl⁄e\', null, $r)',
'@preg_replace(\' ⁄hl⁄e\', null, $r)',
'@preg_replace(\'⁄hl⁄e\', null, $r)',
'@preg_replace(\'  ŸhkŸe\', null, $r)',
'@preg_replace(\' ŸhkŸe\', null, $r)',
'@preg_replace(\'ŸhkŸe\', null, $r)',
'@preg_replace(\' ÿhjÿe\', null, $r)',
'@preg_replace(\'  ÿhjÿe\', null, $r)',
'@preg_replace(\'  ◊hi◊e\', null, $r)',
'@preg_replace(\'ÿhjÿe\', null, $r)',
'@preg_replace(\'◊hi◊e\', null, $r)',
'@preg_replace(\' ◊hi◊e\', null, $r)',
'@preg_replace(\' ÷hh÷e\', null, $r)',
'@preg_replace(\'  ÷hh÷e\', null, $r)',
'@preg_replace(\'  ’hg’e\', null, $r)',
'@preg_replace(\'÷hh÷e\', null, $r)',
'@preg_replace(\'’hg’e\', null, $r)',
'@preg_replace(\' ’hg’e\', null, $r)',
'@preg_replace(\' ‘hf‘e\', null, $r)',
'@preg_replace(\'  ‘hf‘e\', null, $r)',
'@preg_replace(\'  ”he”e\', null, $r)',
'@preg_replace(\'‘hf‘e\', null, $r)',
'@preg_replace(\'ËhzËe\', null, $r)',
'@preg_replace(\'  ÁhyÁe\', null, $r)',
'@preg_replace(\'  ËhzËe\', null, $r)',
'@preg_replace(\' ËhzËe\', null, $r)',
'@preg_replace(\'  ÊhxÊe\', null, $r)',
'@preg_replace(\' ÊhxÊe\', null, $r)',
'@preg_replace(\' ÁhyÁe\', null, $r)',
'@preg_replace(\'ÁhyÁe\', null, $r)',
'@preg_replace(\' ÂhwÂe\', null, $r)',
'@preg_replace(\'ÂhwÂe\', null, $r)',
'@preg_replace(\'ÊhxÊe\', null, $r)',
'@preg_replace(\'  ÂhwÂe\', null, $r)',
'@preg_replace(\'‰hv‰e\', null, $r)',
'@preg_replace(\'  „hu„e\', null, $r)',
'@preg_replace(\'  ‰hv‰e\', null, $r)',
'@preg_replace(\' ‰hv‰e\', null, $r)',
'@preg_replace(\' ‚ht‚e\', null, $r)',
'@preg_replace(\'  ‚ht‚e\', null, $r)',
'@preg_replace(\'„hu„e\', null, $r)',
'@preg_replace(\' „hu„e\', null, $r)',
'@preg_replace(\'·hs·e\', null, $r)',
'@preg_replace(\' ·hs·e\', null, $r)',
'@preg_replace(\'  ·hs·e\', null, $r)',
'@preg_replace(\'‚ht‚e\', null, $r)',
'@preg_replace(\'  ﬂhqﬂe\', null, $r)',
'@preg_replace(\'‡hr‡e\', null, $r)',
'@preg_replace(\' ‡hr‡e\', null, $r)',
'@preg_replace(\'  ‡hr‡e\', null, $r)',
'@preg_replace(\' ﬁhpﬁe\', null, $r)',
'@preg_replace(\'  ﬁhpﬁe\', null, $r)',
'@preg_replace(\'ﬂhqﬂe\', null, $r)',
'@preg_replace(\' ﬂhqﬂe\', null, $r)',
'@preg_replace(\'ÚijÚe\', null, $r)',
'@preg_replace(\'  ÒiiÒe\', null, $r)',
'@preg_replace(\' ÒiiÒe\', null, $r)',
'@preg_replace(\'ÒiiÒe\', null, $r)',
'@preg_replace(\' ÛikÛe\', null, $r)',
'@preg_replace(\'ÛikÛe\', null, $r)',
'@preg_replace(\'  ÚijÚe\', null, $r)',
'@preg_replace(\' ÚijÚe\', null, $r)',
'@preg_replace(\' ÔigÔe\', null, $r)',
'@preg_replace(\'ÔigÔe\', null, $r)',
'@preg_replace(\'  ÓifÓe\', null, $r)',
'@preg_replace(\' ÓifÓe\', null, $r)',
'@preg_replace(\'  ihe\', null, $r)',
'@preg_replace(\' ihe\', null, $r)',
'@preg_replace(\'ihe\', null, $r)',
'@preg_replace(\'  ÔigÔe\', null, $r)',
'@preg_replace(\' ÏidÏe\', null, $r)',
'@preg_replace(\'  ÏidÏe\', null, $r)',
'@preg_replace(\'  ÎicÎe\', null, $r)',
'@preg_replace(\'ÏidÏe\', null, $r)',
'@preg_replace(\'  ÌieÌe\', null, $r)',
'@preg_replace(\'ÓifÓe\', null, $r)',
'@preg_replace(\'ÌieÌe\', null, $r)',
'@preg_replace(\' ÌieÌe\', null, $r)',
'@preg_replace(\'  ÈiaÈe\', null, $r)',
'@preg_replace(\'ÍibÍe\', null, $r)',
'@preg_replace(\'ÈiaÈe\', null, $r)',
'@preg_replace(\' ÈiaÈe\', null, $r)',
'@preg_replace(\'ÎicÎe\', null, $r)',
'@preg_replace(\' ÎicÎe\', null, $r)',
'@preg_replace(\' ÍibÍe\', null, $r)',
'@preg_replace(\'  ÍibÍe\', null, $r)',
'@preg_replace(\'¸it¸e\', null, $r)',
'@preg_replace(\'  ˚is˚e\', null, $r)',
'@preg_replace(\'  ¸it¸e\', null, $r)',
'@preg_replace(\' ¸it¸e\', null, $r)',
'@preg_replace(\' ˝iu˝e\', null, $r)',
'@preg_replace(\'˝iu˝e\', null, $r)',
'@preg_replace(\'˛iv˛e\', null, $r)',
'@preg_replace(\'  ˝iu˝e\', null, $r)',
'@preg_replace(\' ˘iq˘e\', null, $r)',
'@preg_replace(\'˘iq˘e\', null, $r)',
'@preg_replace(\'˙ir˙e\', null, $r)',
'@preg_replace(\'  ˘iq˘e\', null, $r)',
'@preg_replace(\'  ˙ir˙e\', null, $r)',
'@preg_replace(\' ˙ir˙e\', null, $r)',
'@preg_replace(\' ˚is˚e\', null, $r)',
'@preg_replace(\'˚is˚e\', null, $r)',
'@preg_replace(\' ˆinˆe\', null, $r)',
'@preg_replace(\'  ˆinˆe\', null, $r)',
'@preg_replace(\'˜io˜e\', null, $r)',
'@preg_replace(\' ˜io˜e\', null, $r)',
'@preg_replace(\'  ˜io˜e\', null, $r)',
'@preg_replace(\'¯ip¯e\', null, $r)',
'@preg_replace(\' ¯ip¯e\', null, $r)',
'@preg_replace(\'  ¯ip¯e\', null, $r)',
'@preg_replace(\'  ÛikÛe\', null, $r)',
'@preg_replace(\'ÙilÙe\', null, $r)',
'@preg_replace(\' ÙilÙe\', null, $r)',
'@preg_replace(\'  ÙilÙe\', null, $r)',
'@preg_replace(\'ıimıe\', null, $r)',
'@preg_replace(\' ıimıe\', null, $r)',
'@preg_replace(\'  ıimıe\', null, $r)',
'@preg_replace(\'ˆinˆe\', null, $r)',
'@preg_replace(\'  ˇiwˇe\', null, $r)',
'@preg_replace(\' ˇiwˇe\', null, $r)',
'@preg_replace(\'ˇiwˇe\', null, $r)',
'@preg_replace(\'  ˛iv˛e\', null, $r)',
'@preg_replace(\' ˛iv˛e\', null, $r)',
'@preg_replace(\' aee\', null, $r)',
'@preg_replace(\'  aee\', null, $r)',
'@preg_replace(\'  ade\', null, $r)',
'@preg_replace(\'aee\', null, $r)',
'@preg_replace(\'ade\', null, $r)',
'@preg_replace(\' ade\', null, $r)',
'@preg_replace(\' ace\', null, $r)',
'@preg_replace(\'  ace\', null, $r)',
'@preg_replace(\'  abe\', null, $r)',
'@preg_replace(\'ace\', null, $r)',
'@preg_replace(\'abe\', null, $r)',
'@preg_replace(\' abe\', null, $r)',
'@preg_replace(\' aae\', null, $r)',
'@preg_replace(\'  aae\', null, $r)',
'@preg_replace(\'  ze\', null, $r)',
'@preg_replace(\'aae\', null, $r)',
'@preg_replace(\' ze\', null, $r)',
'@preg_replace(\'ze\', null, $r)',
'@preg_replace(\'  ye\', null, $r)',
'@preg_replace(\' ye\', null, $r)',
'@preg_replace(\'ye\', null, $r)',
'@preg_replace(\'  xe\', null, $r)',
'@preg_replace(\' xe\', null, $r)',
'@preg_replace(\'xe\', null, $r)',
'@preg_replace(\'  we\', null, $r)',
'@preg_replace(\' we\', null, $r)',
'@preg_replace(\'we\', null, $r)',
'@preg_replace(\'  ve\', null, $r)',
'@preg_replace(\' ve\', null, $r)',
'@preg_replace(\'ve\', null, $r)',
'@preg_replace(\'  ue\', null, $r)',
'@preg_replace(\' ue\', null, $r)',
'@preg_replace(\'te\', null, $r)',
'@preg_replace(\' te\', null, $r)',
'@preg_replace(\'  te\', null, $r)',
'@preg_replace(\'ue\', null, $r)',
'@preg_replace(\'  re\', null, $r)',
'@preg_replace(\'se\', null, $r)',
'@preg_replace(\' se\', null, $r)',
'@preg_replace(\'  se\', null, $r)',
'@preg_replace(\' qe\', null, $r)',
'@preg_replace(\'  qe\', null, $r)',
'@preg_replace(\'re\', null, $r)',
'@preg_replace(\' re\', null, $r)',
'@preg_replace(\'pe\', null, $r)',
'@preg_replace(\' pe\', null, $r)',
'@preg_replace(\'  pe\', null, $r)',
'@preg_replace(\'qe\', null, $r)',
'@preg_replace(\'oe\', null, $r)',
'@preg_replace(\'  ne\', null, $r)',
'@preg_replace(\'  oe\', null, $r)',
'@preg_replace(\' oe\', null, $r)',
'@preg_replace(\'  me\', null, $r)',
'@preg_replace(\' me\', null, $r)',
'@preg_replace(\' ne\', null, $r)',
'@preg_replace(\'ne\', null, $r)',
'@preg_replace(\' 
l
e\', null, $r)',
'@preg_replace(\'
l
e\', null, $r)',
'@preg_replace(\'me\', null, $r)',
'@preg_replace(\'  
l
e\', null, $r)',
'@preg_replace(\'	k	e\', null, $r)',
'@preg_replace(\'  je\', null, $r)',
'@preg_replace(\'  	k	e\', null, $r)',
'@preg_replace(\' 	k	e\', null, $r)',
'@preg_replace(\'  he\', null, $r)',
/*
'@preg_replace(\'ie\', null, $r)',
'@preg_repl  ie\', null, $r)',
'@preg_replace(\'  ie\', null, $r)',
*/
'@preg_replace(\'he\', null, $r)',
'@preg_replace(\' he\', null, $r)',
'@preg_replace(\'je\', null, $r)',
'@preg_replace(\' je\', null, $r)',
'@preg_replace(\'fe\', null, $r)',
'@preg_replace(\' fe\', null, $r)',
'@preg_replace(\' ee\', null, $r)',
'@preg_replace(\'  ee\', null, $r)',
'@preg_replace(\' ge\', null, $r)',
'@preg_replace(\'  ge\', null, $r)',
'@preg_replace(\'  fe\', null, $r)',
'@preg_replace(\'ge\', null, $r)',
'@preg_replace(\'  ce\', null, $r)',
'@preg_replace(\' ce\', null, $r)',
'@preg_replace(\'ce\', null, $r)',
'@preg_replace(\'   b e\', null, $r)',
'@preg_replace(\'ee\', null, $r)',
'@preg_replace(\'  de\', null, $r)',
'@preg_replace(\' de\', null, $r)',
'@preg_replace(\'de\', null, $r)',
'@preg_replace(\'  b e\', null, $r)',
'@preg_replace(\' b e\', null, $r)',
'@preg_replace(\'xdrxe\', null, $r)',
'@preg_replace(\'  wdqwe\', null, $r)',
'@preg_replace(\'  xdrxe\', null, $r)',
'@preg_replace(\' xdrxe\', null, $r)',
'@preg_replace(\'  vdpve\', null, $r)',
'@preg_replace(\' vdpve\', null, $r)',
'@preg_replace(\' wdqwe\', null, $r)',
'@preg_replace(\'wdqwe\', null, $r)',
'@preg_replace(\' udoue\', null, $r)',
'@preg_replace(\'udoue\', null, $r)',
'@preg_replace(\'vdpve\', null, $r)',
'@preg_replace(\'  udoue\', null, $r)',
'@preg_replace(\'tdnte\', null, $r)',
'@preg_replace(\'  sdmse\', null, $r)',
'@preg_replace(\'  tdnte\', null, $r)',
'@preg_replace(\' tdnte\', null, $r)',
'@preg_replace(\'}dw}e\', null, $r)',
'@preg_replace(\' }dw}e\', null, $r)',
'@preg_replace(\'  }dw}e\', null, $r)',
'@preg_replace(\'~dx~e\', null, $r)',
'@preg_replace(\'  {du}e\', null, $r)',
'@preg_replace(\'|dv|e\', null, $r)',
'@preg_replace(\' |dv|e\', null, $r)',
'@preg_replace(\'  |dv|e\', null, $r)',
'@preg_replace(\' zdtze\', null, $r)',
'@preg_replace(\'  zdtze\', null, $r)',
'@preg_replace(\'{du}e\', null, $r)',
'@preg_replace(\' {du}e\', null, $r)',
'@preg_replace(\'ydsye\', null, $r)',
'@preg_replace(\' ydsye\', null, $r)',
'@preg_replace(\'  ydsye\', null, $r)',
'@preg_replace(\'zdtze\', null, $r)',
'@preg_replace(\'ndhne\', null, $r)',
'@preg_replace(\'  mdgme\', null, $r)',
'@preg_replace(\' mdgme\', null, $r)',
'@preg_replace(\'mdgme\', null, $r)',
'@preg_replace(\'  ldfle\', null, $r)',
'@preg_replace(\' ldfle\', null, $r)',
'@preg_replace(\'ldfle\', null, $r)',
'@preg_replace(\'  kdeke\', null, $r)',
'@preg_replace(\' kdeke\', null, $r)',
'@preg_replace(\'kdeke\', null, $r)',
'@preg_replace(\'  jddje\', null, $r)',
'@preg_replace(\' jddje\', null, $r)',
'@preg_replace(\'jddje\', null, $r)',
'@preg_replace(\'  idcie\', null, $r)',
'@preg_replace(\' idcie\', null, $r)',
'@preg_replace(\'idcie\', null, $r)',
'@preg_replace(\'sdmse\', null, $r)',
'@preg_replace(\' sdmse\', null, $r)',
'@preg_replace(\' rdlre\', null, $r)',
'@preg_replace(\'  rdlre\', null, $r)',
'@preg_replace(\'  qdkqe\', null, $r)',
'@preg_replace(\'rdlre\', null, $r)',
'@preg_replace(\'qdkqe\', null, $r)',
'@preg_replace(\' qdkqe\', null, $r)',
'@preg_replace(\' pdjpe\', null, $r)',
'@preg_replace(\'  pdjpe\', null, $r)',
'@preg_replace(\'  odioe\', null, $r)',
'@preg_replace(\'pdjpe\', null, $r)',
'@preg_replace(\'odioe\', null, $r)',
'@preg_replace(\' odioe\', null, $r)',
'@preg_replace(\' ndhne\', null, $r)',
'@preg_replace(\'  ndhne\', null, $r)',
'@preg_replace(\' acuae\', null, $r)',
'@preg_replace(\'acuae\', null, $r)',
'@preg_replace(\'bcvbe\', null, $r)',
'@preg_replace(\'  acuae\', null, $r)',
'@preg_replace(\'  bcvbe\', null, $r)',
'@preg_replace(\' bcvbe\', null, $r)',
'@preg_replace(\' ccwce\', null, $r)',
'@preg_replace(\'ccwce\', null, $r)',
'@preg_replace(\'  ^cr^e\', null, $r)',
'@preg_replace(\' ^cr^e\', null, $r)',
'@preg_replace(\' _cs_e\', null, $r)',
'@preg_replace(\'_cs_e\', null, $r)',
'@preg_replace(\'`ct`e\', null, $r)',
'@preg_replace(\'  _cs_e\', null, $r)',
'@preg_replace(\'  `ct`e\', null, $r)',
'@preg_replace(\' `ct`e\', null, $r)',
'@preg_replace(\' fczfe\', null, $r)',
'@preg_replace(\'  fczfe\', null, $r)',
'@preg_replace(\'gdage\', null, $r)',
'@preg_replace(\' gdage\', null, $r)',
'@preg_replace(\'  gdage\', null, $r)',
'@preg_replace(\'hdbhe\', null, $r)',
'@preg_replace(\' hdbhe\', null, $r)',
'@preg_replace(\'  hdbhe\', null, $r)',
'@preg_replace(\'  ccwce\', null, $r)',
'@preg_replace(\'dcxde\', null, $r)',
'@preg_replace(\' dcxde\', null, $r)',
'@preg_replace(\'  dcxde\', null, $r)',
'@preg_replace(\'ecyee\', null, $r)',
'@preg_replace(\' ecyee\', null, $r)',
'@preg_replace(\'  ecyee\', null, $r)',
'@preg_replace(\'fczfe\', null, $r)',
'@preg_replace(\' WckWe\', null, $r)',
'@preg_replace(\'WckWe\', null, $r)',
'@preg_replace(\'  VcjVe\', null, $r)',
'@preg_replace(\' VcjVe\', null, $r)',
'@preg_replace(\'  XclXe\', null, $r)',
'@preg_replace(\' XclXe\', null, $r)',
'@preg_replace(\'XclXe\', null, $r)',
'@preg_replace(\'  WckWe\', null, $r)',
'@preg_replace(\'  TchTe\', null, $r)',
'@preg_replace(\' TchTe\', null, $r)',
'@preg_replace(\'TchTe\', null, $r)',
'@preg_replace(\'  ScgSe\', null, $r)',
'@preg_replace(\'VcjVe\', null, $r)',
'@preg_replace(\'  UciUe\', null, $r)',
'@preg_replace(\' UciUe\', null, $r)',
'@preg_replace(\'UciUe\', null, $r)',
'@preg_replace(\' \\\\cp\\\\e\', null, $r)',
'@preg_replace(\'  \\\\cp\\\\e\', null, $r)',
'@preg_replace(\'\\\\cp\\\\e\', null, $r)',
'@preg_replace(\'  [co]e\', null, $r)',
'@preg_replace(\'  ]cq]e\', null, $r)',
'@preg_replace(\'^cr^e\', null, $r)',
'@preg_replace(\']cq]e\', null, $r)',
'@preg_replace(\' ]cq]e\', null, $r)',
'@preg_replace(\'  YcmYe\', null, $r)',
'@preg_replace(\'ZcnZe\', null, $r)',
'@preg_replace(\'YcmYe\', null, $r)',
'@preg_replace(\' YcmYe\', null, $r)',
'@preg_replace(\'[co]e\', null, $r)',
'@preg_replace(\' [co]e\', null, $r)',
'@preg_replace(\' ZcnZe\', null, $r)',
'@preg_replace(\'  ZcnZe\', null, $r)',
'@preg_replace(\' JbxJe\', null, $r)',
'@preg_replace(\'  JbxJe\', null, $r)',
'@preg_replace(\'KbyKe\', null, $r)',
'@preg_replace(\' KbyKe\', null, $r)',
'@preg_replace(\'IbwIe\', null, $r)',
'@preg_replace(\' IbwIe\', null, $r)',
'@preg_replace(\'  IbwIe\', null, $r)',
'@preg_replace(\'JbxJe\', null, $r)',
'@preg_replace(\'McaMe\', null, $r)',
'@preg_replace(\' McaMe\', null, $r)',
'@preg_replace(\'  McaMe\', null, $r)',
'@preg_replace(\'NcbNe\', null, $r)',
'@preg_replace(\'  KbyKe\', null, $r)',
'@preg_replace(\'LbzLe\', null, $r)',
'@preg_replace(\' LbzLe\', null, $r)',
'@preg_replace(\'  LbzLe\', null, $r)',
'@preg_replace(\'PcdPe\', null, $r)',
'@preg_replace(\'  OccOe\', null, $r)',
'@preg_replace(\'  PcdPe\', null, $r)',
'@preg_replace(\' PcdPe\', null, $r)',
'@preg_replace(\'  NcbNe\', null, $r)',
'@preg_replace(\' NcbNe\', null, $r)',
'@preg_replace(\' OccOe\', null, $r)',
'@preg_replace(\'OccOe\', null, $r)',
'@preg_replace(\'  RcfRe\', null, $r)',
'@preg_replace(\' RcfRe\', null, $r)',
'@preg_replace(\' ScgSe\', null, $r)',
'@preg_replace(\'ScgSe\', null, $r)',
'@preg_replace(\' QceQe\', null, $r)',
'@preg_replace(\'QceQe\', null, $r)',
'@preg_replace(\'RcfRe\', null, $r)',
'@preg_replace(\'  QceQe\', null, $r)',
'@preg_replace(\' @bn@e\', null, $r)',
'@preg_replace(\'  @bn@e\', null, $r)',
'@preg_replace(\'  ?bm?e\', null, $r)',
'@preg_replace(\'@bn@e\', null, $r)',
'@preg_replace(\'?bm?e\', null, $r)',
'@preg_replace(\' ?bm?e\', null, $r)',
'@preg_replace(\' >bl>e\', null, $r)',
'@preg_replace(\'  >bl>e\', null, $r)',
'@preg_replace(\'CbqCe\', null, $r)',
'@preg_replace(\' CbqCe\', null, $r)',
'@preg_replace(\' BbpBe\', null, $r)',
'@preg_replace(\'  BbpBe\', null, $r)',
'@preg_replace(\'  AboAe\', null, $r)',
'@preg_replace(\'BbpBe\', null, $r)',
'@preg_replace(\'AboAe\', null, $r)',
'@preg_replace(\' AboAe\', null, $r)',
'@preg_replace(\'FbtFe\', null, $r)',
'@preg_replace(\'  EbsEe\', null, $r)',
'@preg_replace(\' EbsEe\', null, $r)',
'@preg_replace(\'EbsEe\', null, $r)',
'@preg_replace(\'  DbrDe\', null, $r)',
'@preg_replace(\' DbrDe\', null, $r)',
'@preg_replace(\'DbrDe\', null, $r)',
'@preg_replace(\'  CbqCe\', null, $r)',
'@preg_replace(\'  HbvHe\', null, $r)',
'@preg_replace(\' HbvHe\', null, $r)',
'@preg_replace(\'HbvHe\', null, $r)',
'@preg_replace(\'  GbuGe\', null, $r)',
'@preg_replace(\' GbuGe\', null, $r)',
'@preg_replace(\'GbuGe\', null, $r)',
'@preg_replace(\'  FbtFe\', null, $r)',
'@preg_replace(\' FbtFe\', null, $r)',
'@preg_replace(\'  )aq)e\', null, $r)',
'@preg_replace(\'*ar*e\', null, $r)',
'@preg_replace(\' *ar*e\', null, $r)',
'@preg_replace(\'  *ar*e\', null, $r)',
'@preg_replace(\'+as+e\', null, $r)',
'@preg_replace(\' +as+e\', null, $r)',
'@preg_replace(\'  +as+e\', null, $r)',
'@preg_replace(\',at,e\', null, $r)',
'@preg_replace(\' ,at,e\', null, $r)',
'@preg_replace(\'  ,at,e\', null, $r)',
'@preg_replace(\'-au-e\', null, $r)',
'@preg_replace(\' -au-e\', null, $r)',
'@preg_replace(\'  -au-e\', null, $r)',
'@preg_replace(\'.av.e\', null, $r)',
'@preg_replace(\' .av.e\', null, $r)',
'@preg_replace(\'  .av.e\', null, $r)',
'@preg_replace(\' /aw/e\', null, $r)',
'@preg_replace(\'/aw/e\', null, $r)',
'@preg_replace(\':bh:e\', null, $r)',
'@preg_replace(\'  /aw/e\', null, $r)',
'@preg_replace(\'  :bh:e\', null, $r)',
'@preg_replace(\' :bh:e\', null, $r)',
'@preg_replace(\' ;bi;e\', null, $r)',
'@preg_replace(\';bi;e\', null, $r)',
'@preg_replace(\'<bj<e\', null, $r)',
'@preg_replace(\'  ;bi;e\', null, $r)',
'@preg_replace(\'  <bj<e\', null, $r)',
'@preg_replace(\' <bj<e\', null, $r)',
'@preg_replace(\' =bk=e\', null, $r)',
'@preg_replace(\'=bk=e\', null, $r)',
'@preg_replace(\'>bl>e\', null, $r)',
'@preg_replace(\'  =bk=e\', null, $r)',
'@preg_replace(\'  afe\', null, $r)',
'@preg_replace(\'age\', null, $r)',
'@preg_replace(\'afe\', null, $r)',
'@preg_replace(\' afe\', null, $r)',
'@preg_replace(\' ah e\', null, $r)',
'@preg_replace(\'  ah e\', null, $r)',
'@preg_replace(\' age\', null, $r)',
'@preg_replace(\'  age\', null, $r)',
'@preg_replace(\' !ai!e\', null, $r)',
'@preg_replace(\'  !ai!e\', null, $r)',
'@preg_replace(\'   ah e\', null, $r)',
'@preg_replace(\'!ai!e\', null, $r)',
'@preg_replace(\'  "aj"e\', null, $r)',
'@preg_replace(\'#ak#e\', null, $r)',
'@preg_replace(\'"aj"e\', null, $r)',
'@preg_replace(\' "aj"e\', null, $r)',
'@preg_replace(\' $al$e\', null, $r)',
'@preg_replace(\'$al$e\', null, $r)',
'@preg_replace(\'  #ak#e\', null, $r)',
'@preg_replace(\' #ak#e\', null, $r)',
'@preg_replace(\'  %am%e\', null, $r)',
'@preg_replace(\' %am%e\', null, $r)',
'@preg_replace(\'%am%e\', null, $r)',
'@preg_replace(\'  $al$e\', null, $r)',
'@preg_replace(\'(ap)e\', null, $r)',
'@preg_replace(\'  &an&e\', null, $r)',
'@preg_replace(\' &an&e\', null, $r)',
'@preg_replace(\'&an&e\', null, $r)',
'@preg_replace(\' )aq)e\', null, $r)',
'@preg_replace(\')aq)e\', null, $r)',
'@preg_replace(\'  (ap)e\', null, $r)',
'@preg_replace(\' (ap)e\', null, $r)',
                     );

$expected_not = array('@preg_replace(\'GbuGe\', null, $r))',
                      '@preg_replace(\' GbuGe\', null, $r))',
                      '@preg_replace(\'  GbuGe\', null, $r))',
                     );

?>