<?php

$expected     = array('"b"',
                      '"b"',
                      '"b"',
                      '"b"',
                      '"b"',
                      '"b"',
                      '"b"',
                      '"b"',
                      '"b"',
                      '"b"',
                      '"b"',
                      '"b"',
                      'd',
                      'd',
                      'd',
                      'd',
                      'd',
                      'd',
                      'd',
                      'd',
                      'd',
                      'd',
                      'd',
                      'd',
                      '"b"',
                      '"b"',
                      '"b"',
                      'd',
                      'd',
                      'd',
                      'd',
                      'd',
                     );

$expected_not = array('$x',
                      '{$x}',
                      'a',
                     );

?>