#!/usr/bin/php 
<?php

$test = $argv[1];

$ini = file_get_contents('../../projects/test/config.ini');

$iniNeojImport = preg_replace("/([^;])loader = 'CypherG3'/is", "\\1;loader = 'CypherG3'", $ini);
$iniNeojImport = preg_replace("/;loader = 'Neo4jImport'/is", "loader = 'Neo4jImport'", $iniNeojImport);

file_put_contents('../../projects/test/config.ini', $iniNeojImport);

echo shell_exec('phpunit '.$test);

$iniCypher = preg_replace("/([^;])loader = 'Neo4jImport'/is", "\\1;loader = 'Neo4jImport'", $ini);
$iniCypher = preg_replace("/;loader = 'CypherG3'/is", "loader = 'CypherG3'", $iniCypher);

file_put_contents('../../projects/test/config.ini', $iniCypher);

echo shell_exec('phpunit '.$test);

// restore initial
file_put_contents('../../projects/test/config.ini', $ini);

?>